# 线上配置文件

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://rm-bp166g0906g2pd9skro.mysql.rds.aliyuncs.com/user_center?useSSL=false'
    username: user0
    password: aA1357924680
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0

